networks:
  chalapao-network:
    driver: bridge

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_PASSWORD=pookiebear
      - POSTGRESQL_USERNAME=server
      - POSTGRESQL_DATABASE=chalapao
    ports:
      - '5439:5432'
    networks:
      - chalapao-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - chalapao-network
    environment:
      - PORT=8000
      - PGHOST=postgres
    env_file:
      - backend/.env
    depends_on:
      - postgresql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - chalapao-network
    depends_on:
      - backend
    environment:
      - DATABASE_URL=postgres://server:pookiebear@postgres:5439/chalapao
      - BACKEND_URL=http://backend:8000
    env_file:
      - frontend/.env


