

name: Bug report
description: File a bug report.
title: "Bug: "
labels: ["bug"]
assignees:
  - somxhai
body:
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the issue.
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Provide steps to reproduce the behavior.
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Links? References issue? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false



