export interface UserInfo {
  id?: string; // UUID, generated by DB
  first_name: string;
  last_name: string;
  gender?: "M" | "F" | "O"; // Optional if nullable
  birth_date: string; // or Date
  citizen_id: string;
  phone_number?: string | null; // nullable
  created_at?: string; // or Date
  updated_at?: string; // or Date
}

export interface Address {
  id?: string;
  user_id: string;
  is_primary: boolean;
  residence_info: string;
  sub_district: string;
  district: string;
  province: string;
  postal_code: string;
  created_at?: string;
  updated_at?: string;
}
