import { UUIDTypes } from "uuid";

export type UserInfoRequest = Omit<
  UserInfo,
  "id" | "created_at" | "updated_at"
>;
export interface UserInfo {
  id?: UUIDTypes; // UUID, generated by DB
  user_id: UUIDTypes;
  first_name: string;
  last_name: string;
  gender?: "M" | "F" | "O"; // Optional if nullable
  birth_date: Date; // or Date
  citizen_id: string;
  phone_number?: string | null; // nullable
  created_at?: Date; // or Date
  updated_at?: Date; // or Date
}

export interface Address {
  id?: string;
  user_id: string;
  is_primary?: boolean;
  residence_info: string;
  sub_district: string;
  district: string;
  province: string;
  postal_code: string;
  created_at?: string;
  updated_at?: string;
}
